In [1]:
import pandas as pd
import numpy as np

In [2]:
#download from "https://www.reinfolib.mlit.go.jp/realEstatePrices/""
df = pd.read_csv('../raw_data/aichi_20071_20234.csv', encoding="cp932", on_bad_lines='skip')

In [3]:
df = df.drop(columns=['市区町村コード'])
df = df.drop(columns=['価格情報区分'])
df = df.drop(columns=['建物の構造'])
df = df.drop(columns=['用途'])
df = df.drop(columns=['今後の利用目的'])
df = df.drop(columns=['都市計画'])
df = df.drop(columns=['建ぺい率（％）'])
df = df.drop(columns=['容積率（％）'])
df = df.drop(columns=['改装'])
df = df.drop(columns=['取引の事情等'])

In [4]:
df.head()

,種類,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,取引価格（総額）,間取り,面積（㎡）,建築年,取引時期
0,中古マンション等,愛知県,名古屋市千種区,揚羽町,茶屋ケ坂,3,19000000,３ＬＤＫ,90,1986年,2021年第1四半期
1,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),8,10000000,２ＬＤＫ,65,1972年,2021年第1四半期
2,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),9,33000000,３ＬＤＫ,85,2000年,2021年第1四半期
3,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),13,7000000,３ＬＤＫ,65,1970年,2021年第1四半期
4,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),7,13000000,２ＬＤＫ,75,1980年,2021年第1四半期

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51931 entries, 0 to 51930
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   種類         51931 non-null  object
 1   都道府県名      51931 non-null  object
 2   市区町村名      51931 non-null  object
 3   地区名        51931 non-null  object
 4   最寄駅：名称     50896 non-null  object
 5   最寄駅：距離（分）  49862 non-null  object
 6   取引価格（総額）   51931 non-null  int64
 7   間取り        50750 non-null  object
 8   面積（㎡）      51931 non-null  int64
 9   建築年        50257 non-null  object
 10  取引時期       51931 non-null  object
dtypes: int64(2), object(9)
memory usage: 4.4+ MB

In [6]:
df['取引価格（総額）'] = df['取引価格（総額）']/10000

In [7]:
df['取引時期（年）'] = df['取引時期'].str[:4]

In [8]:
# Get the current year
current_year = pd.Timestamp.now().year

In [9]:
# Step 1: Remove '年' character
df['建築年'] = df['建築年'].str.replace('年', '')

# Step 2: Drop rows with the value '戦前'
df = df[df['建築年'] != '戦前']

# Step 3: Convert to numeric, coercing errors to NaN
df['建築年'] = pd.to_numeric(df['建築年'], errors='coerce')

# Step 4: Fill NaN values with a placeholder or drop them
df['建築年'].fillna(0, inplace=True)  # Example: Fill with 0, or you can choose to drop these rows

# Get the current year
current_year = pd.Timestamp.now().year

# Step 5: Calculate the age of the building and add as new column '築年数'
df['築年数'] = current_year - df['建築年'].astype(int)

In [10]:
df.head()

,種類,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,取引価格（総額）,間取り,面積（㎡）,建築年,取引時期,取引時期（年）,築年数
0,中古マンション等,愛知県,名古屋市千種区,揚羽町,茶屋ケ坂,3,1900.0,３ＬＤＫ,90,1986.0,2021年第1四半期,2021,38
1,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),8,1000.0,２ＬＤＫ,65,1972.0,2021年第1四半期,2021,52
2,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),9,3300.0,３ＬＤＫ,85,2000.0,2021年第1四半期,2021,24
3,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),13,700.0,３ＬＤＫ,65,1970.0,2021年第1四半期,2021,54
4,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),7,1300.0,２ＬＤＫ,75,1980.0,2021年第1四半期,2021,44

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51900 entries, 0 to 51930
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   種類         51900 non-null  object
 1   都道府県名      51900 non-null  object
 2   市区町村名      51900 non-null  object
 3   地区名        51900 non-null  object
 4   最寄駅：名称     50865 non-null  object
 5   最寄駅：距離（分）  49831 non-null  object
 6   取引価格（総額）   51900 non-null  float64
 7   間取り        50720 non-null  object
 8   面積（㎡）      51900 non-null  int64
 9   建築年        51900 non-null  float64
 10  取引時期       51900 non-null  object
 11  取引時期（年）    51900 non-null  object
 12  築年数        51900 non-null  int64
dtypes: float64(2), int64(2), object(9)
memory usage: 5.5+ MB

In [12]:
df['取引時期（年）'] = df['取引時期（年）'].astype(int)
df['建築年'] = df['建築年'].astype(int)

In [13]:
df.head()

,種類,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,取引価格（総額）,間取り,面積（㎡）,建築年,取引時期,取引時期（年）,築年数
0,中古マンション等,愛知県,名古屋市千種区,揚羽町,茶屋ケ坂,3,1900.0,３ＬＤＫ,90,1986,2021年第1四半期,2021,38
1,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),8,1000.0,２ＬＤＫ,65,1972,2021年第1四半期,2021,52
2,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),9,3300.0,３ＬＤＫ,85,2000,2021年第1四半期,2021,24
3,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),13,700.0,３ＬＤＫ,65,1970,2021年第1四半期,2021,54
4,中古マンション等,愛知県,名古屋市千種区,鹿子町,本山(愛知),7,1300.0,２ＬＤＫ,75,1980,2021年第1四半期,2021,44

In [14]:
df['建築年'] = df['建築年'].astype(int)

In [15]:
df.to_csv("../data/aichi_20071_20234_preprocessed.csv", index=False, encoding='utf-8-sig')